### PR TITLE
Finished with signup.js for now.

### PR DESCRIPTION
**Pull request by mssugarpop**
Related issue(#): [125](https://github.com/SEI-2121/blltn-brd/issues/125)
Description of Changes Made: I edited the fetch for createUser function for Signup.js
Questions/Comments for Reviewer: It makes sense to me that for "Create User" that it would through Signup, so I just put it in the Signup.js. If it should be different, please let me know.

### CODE REVIEW

**Comment by mssugarpop** [comment]
Will comment again when I feel that it's ready to actually check. Please wait.

**Comment by mssugarpop** [comment]
Okay. It SHOULD be good.

**Comment by ghost** [comment]
@ewalker991 - Build failed Due to this error: 

``` 
4:40:25 PM: src/components/ProjectCard/index.js
4:40:25 PM:   Line 5:10:  'Link' is defined but never used  no-unused-vars 
```

**Review by maker-jws — APPROVED** [review]
Added comment on PR #143 - may need to add redirect after edit for update fetch - redirect path should point back to project detail page

**Pull request merged**
