### PR TITLE
instantiated users app and User model

### PR DESCRIPTION
**Pull request by bryan-emerson**
Related issue(#): #35 

Description of Changes Made: started users app in backend directory and created a User model

Questions/Comments for Reviewer: is None the proper placeholder when our foreign key model does not exist yet?

### CODE REVIEW

**Review by Underwaterr — CHANGES_REQUESTED** [review]
Actually, let's go ahead and implement all four models so we don't have any weird leftover fields.

**Comment by bryan-emerson** [comment]
Pushed up Link, Project, and Screenshot models.

Should ```screenshots``` in the ```Project``` model be plural as shown in the ERD? or should it match ```screenshot``` in the ```Screenshot``` model?

Please carefully review my foreign key/ on delete/Cascade  model attributes. I think I have them set up correctly to delete based on applicable model relationships (i.e. if a Project gets deleted, applicable screenshots will be deleted)

are my dunder str functions returning the correct values? I have them returning the highest level relationship attribute currently ( i.e. screenshot dunder str returns self.project & all others return self.username)

**Review by Underwaterr — CHANGES_REQUESTED** [review]
Incorporate feedback from this morning's meeting

**Comment by bryan-emerson** [comment]
discussed changed have been implemented in reference to the updated ERD

**Review by Underwaterr — APPROVED** [review]

**Pull request merged**
